apiVersion: v1
kind: Secret
metadata:
  name: go-service-basic-airbrake-secret
  labels:
    name: go-service-basic-airbrake-secret
    app: go-service-basic
type: Opaque
data:
  host: {{.ExpandEnv "${APP_SECRETS_ROOT}/airbrake/host" | .Cat | .ToBase64}}
  projectid: {{.ExpandEnv "${APP_SECRETS_ROOT}/airbrake/projectid" | .Cat | .ToBase64}}
  projectkey: {{.ExpandEnv "${APP_SECRETS_ROOT}/airbrake/projectkey" | .Cat | .ToBase64}}