apiVersion: v1
kind: ReplicationController
metadata:
  name: go-service-basic
  labels:
    name: go-service-basic
    app: go-service-basic
spec:
  replicas: 1
  selector:
    name: go-service-basic
  template:
    metadata:
      labels:
        name: go-service-basic
    spec:
      volumes:
      - name: db-secrets-volume
        secret:
          secretName: go-service-basic-db-secrets
      containers:
      - name: app
        image: johnnylai/go-service-basic
        env:
        - name: GIN_MODE
          value: release
        - name: DB_ENV_MYSQL_ROOT_PASSWORD
          value: whatever
        volumeMounts:
        - name: db-secrets-volume
          mountPath: /etc/db-secrets
          readOnly: true
        ports:
        - containerPort: 8080
