apiVersion: v1
kind: Service
metadata:
  name: go-service-basic
  labels:
    name: go-service-basic
    app: go-service-basic
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: go-service-basic