apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Env "PO_APP_NAME"}}
  labels:
    name: {{.Env "PO_APP_NAME"}}
    app: {{.Env "APP_NAME"}}
spec:
  replicas: 1
  selector:
    name: {{.Env "PO_APP_NAME"}}
  template:
    metadata:
      labels:
        name: {{.Env "PO_APP_NAME"}}
    spec:
      volumes:
      - name: db-secrets-volume
        secret:
          secretName: {{.Env "SECRET_DB_NAME"}}
      containers:
      - name: app
        image: {{.Env "PO_APP_IMAGE"}}
        env:
        - name: GIN_MODE
          value: debug
        - name: DB_ENV_MYSQL_ROOT_PASSWORD
          value: whatever
        volumeMounts:
        - name: db-secrets-volume
          mountPath: /etc/db-secrets
          readOnly: true
        ports:
        - containerPort: 8080
