apiVersion: v1
kind: ReplicationController
metadata:
  name: go-service-basic
  labels:
    name: go-service-basic
    app: go-service-basic
spec:
  replicas: 1
  selector:
    name: go-service-basic
  template:
    metadata:
      labels:
        name: go-service-basic
    spec:
      imagePullPolicy: Always
      volumes:
      - name: airbrake-secrets-volume
        secret:
          secretName: go-service-basic-airbrake-secret
      - name: db-secrets-volume
        secret:
          secretName: go-service-basic-db-secret
      - name: newrelic-secrets-volume
        secret:
          secretName: go-service-basic-newrelic-secret
      containers:
      - name: app
        image: johnnylai/go-service-basic:{{.Env "COMMIT"}}
        env:
        - name: GIN_MODE
          value: debug
        volumeMounts:
        - name: airbrake-secrets-volume
          mountPath: /etc/secrets/airbrake
          readOnly: true
        - name: db-secrets-volume
          mountPath: /etc/secrets/db
          readOnly: true
        - name: newrelic-secrets-volume
          mountPath: /etc/secrets/newrelic
          readOnly: true
        ports:
        - containerPort: 8080
