apiVersion: v1
kind: ReplicationController
metadata:
  name: go-service-basic-db
  labels:
    name: go-service-basic-db
    app: go-service-basic
spec:
  replicas: 1
  selector:
    name: go-service-basic-db
  template:
    metadata:
      labels:
        name: go-service-basic-db
    spec:
      containers:
      - name: db
        image: johnnylai/go-service-basic-testdb:{{.Env "COMMIT"}}
        ports:
        - containerPort: 3306
