apiVersion: v1
kind: ReplicationController
metadata:
  name: {{.Env "PO_DB_NAME"}}
  labels:
    name: {{.Env "PO_DB_NAME"}}
    app: {{.Env "APP_NAME"}}
spec:
  replicas: 1
  selector:
    name: {{.Env "PO_DB_NAME"}}
  template:
    metadata:
      labels:
        name: {{.Env "PO_DB_NAME"}}
    spec:
      containers:
      - name: db
        image: {{.Env "PO_DB_IMAGE"}}
        ports:
        - containerPort: 3306
