apiVersion: v1
kind: ReplicationController
metadata:
  name: ${PO_DB_NAME}
  labels:
    name: ${PO_DB_NAME}
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    name: ${PO_DB_NAME}
  template:
    metadata:
      labels:
        name: ${PO_DB_NAME}
    spec:
      containers:
      - name: db
        image: ${PO_DB_IMAGE}
        ports:
        - containerPort: 3306
