apiVersion: v1
kind: Secret
metadata:
  name: {{.Env "SECRET_DB_NAME"}}
  labels:
    name: {{.Env "SECRET_DB_NAME"}}
    app: {{.Env "APP_NAME"}}
type: Opaque
data:
  password: cGFzc3dvcmQK
  username: cm9vdAo=