apiVersion: v1
kind: Secret
metadata:
  name: go-service-basic-db-secrets
  labels:
    name: go-service-basic-db-secrets
    app: go-service-basic
type: Opaque
data:
  password: cGFzc3dvcmQK
  username: cm9vdAo=