apiVersion: v1
kind: Service
metadata:
  name: go-service-basic-db
  labels:
    name: go-service-basic-db
    app: go-service-basic
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
    nodePort: 0
  selector:
    name: go-service-basic-db