apiVersion: v1
kind: Service
metadata:
  name: {{.Env "SVC_DB_NAME"}}
  labels:
    name: {{.Env "SVC_DB_NAME"}}
    app: {{.Env "APP_NAME"}}
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: {{.Env "PO_DB_NAME"}}