apiVersion: v1
kind: Secret
metadata:
  name: go-service-basic-db-secret
  labels:
    name: go-service-basic-db-secret
    app: go-service-basic
type: Opaque
data:
  password: {{.ExpandEnv "${APP_SECRETS_ROOT}/db/password" | .Cat | .ToBase64}}
  username: {{.ExpandEnv "${APP_SECRETS_ROOT}/db/username" | .Cat | .ToBase64}}