apiVersion: v1
kind: Secret
metadata:
  name: go-service-basic-db-secret
  labels:
    name: go-service-basic-db-secret
    app: go-service-basic
type: Opaque
data:
  password: d2hhdGV2ZXI=
  username: cm9vdA==