apiVersion: v1
kind: Secret
metadata:
  name: go-service-basic-newrelic-secret
  labels:
    name: go-service-basic-newrelic-secret
    app: go-service-basic
type: Opaque
data:
  licensekey: {{.ExpandEnv "${APP_SECRETS_ROOT}/newrelic/licensekey" | .Cat | .ToBase64}}