svchost: :8080
db:
  user: root
  password:
  host: localhost
  database: go-service-basic
airbrake:
  projectid: 1234
  projectkey: FIXME
newrelic:
  licensekey: FIXME
  appname: go-service-basic
  verbose: false