svchost: :8080
db:
  user: {{.Cat "/etc/secrets/db/username"}}
  password: {{.Cat "/etc/secrets/db/password"}}
  host: {{.Env "GO_SERVICE_BASIC_DB_PORT_3306_TCP_ADDR"}}
  database: go-service-basic
airbrake:
  projectid: 1234
  projectkey: FIXME
newrelic:
  licensekey: {{.Cat "/etc/secrets/newrelic/licensekey"}}
  appname: go-service-basic.coupadev.com
  verbose: true