svchost: :8080
db:
  user: {{.Cat "/etc/secrets/db/username"}}
  password: {{.Cat "/etc/secrets/db/password"}}
  host: {{.Env "GO_SERVICE_BASIC_DB_PORT_3306_TCP_ADDR"}}
  database: go-service-basic
airbrake:
  host: {{.Cat "/etc/secrets/airbrake/host"}}
  projectid: {{.Cat "/etc/secrets/airbrake/projectid"}}
  projectkey: {{.Cat "/etc/secrets/airbrake/projectkey"}}
newrelic:
  licensekey: {{.Cat "/etc/secrets/newrelic/licensekey"}}
  appname: go-service-basic
  verbose: false